export default {
  maxexpandId: 95,
  treelist: [{
    id: 1,
    name: '北京市',
    ProSort: 1,
    remark: '直辖市',
    pid: '',
    isEdit: false,
    children: [{
      id: 35,
      name: '朝阳区',
      pid: 1,
      remark: '',
      isEdit: false,
      children: []
    }, {
      id: 36,
      name: '海淀区',
      pid: 1,
      remark: '',
      isEdit: false,
      children: []
    }, {
      id: 37,
      name: '房山区',
      pid: 1,
      remark: '',
      isEdit: false,
      children: []
    }, {
      id: 38,
      name: '丰台区',
      pid: 1,
      remark: '',
      isEdit: false,
      children: []
    }, {
      id: 39,
      name: '昌平区',
      pid: 1,
      remark: '',
      isEdit: false,
      children: []
    }, {
      id: 40,
      name: '大兴区',
      pid: 1,
      remark: '',
      isEdit: false,
      children: []
    }]
  }]
}
